TRAIN_DATA = [
    ("Hast du das Messer in der Küche gesehen?", {"entities": [(3, "TOOL")]}),
    ("Ich habe den Lötkolben im Werkzeugschrank gelassen.", {"entities": [(3, "TOOL")]}),
    ("Kannst du mir bitte die Zirkel geben?", {"entities": [(5, "TOOL")]}),
    ("Ich kann den Steckschlüssel nicht finden.", {"entities": [(3, "TOOL")]}),
    ("Benötigst du einen Schraubstock für diese Aufgabe?", {"entities": [(3, "TOOL")]}),
    ("Hat jemand den Feile benutzt?", {"entities": [(3, "TOOL")]}),
    ("Die Tackerklammern sind fast leer.", {"entities": [(1, "TOOL")]}),
    ("Ich brauche eine neue Gehrungssäge für mein Holzprojekt.", {"entities": [(4, "TOOL")]}),
    ("Wo hast du die Kneifzange gelassen?", {"entities": [(3, "TOOL")]}),
    ("Ich kann den Fräser nicht in der Werkzeugkiste finden.", {"entities": [(3, "TOOL")]}),
    ("Hast du die Rohrzange benutzt?", {"entities": [(3, "TOOL")]}),
    ("Ich finde den Abzieher nicht.", {"entities": [(3, "TOOL")]}),
    ("Wo hast du die Luftpumpe gelassen?", {"entities": [(4, "TOOL")]}),
    ("Kannst du mir den Fuchsschwanz geben?", {"entities": [(4, "TOOL")]}),
    ("Wo ist der Kreuzschlitzschraubendreher?", {"entities": [(3, "TOOL")]}),
    ("Hast du einen Inbusschlüssel?", {"entities": [(3, "TOOL")]}),
    ("Ich habe die Kettensäge im Garten gelassen.", {"entities": [(3, "TOOL")]}),
    ("Kannst du die Schubkarre bewegen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Pinzette gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Akkuschrauber?", {"entities": [(3, "TOOL")]}),
    ("Kannst du mir die Nagelfeile geben?", {"entities": [(4, "TOOL")]}),
    ("Benötigst du eine Rohrschneider?", {"entities": [(3, "TOOL")]}),
    ("Die Heißklebepistole ist bereit.", {"entities": [(1, "TOOL")]}),
    ("Ich habe die Drahtbürste verloren.", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Drehmomentschlüssel?", {"entities": [(3, "TOOL")]}),
    ("Ich brauche einen Flachmeißel.", {"entities": [(3, "TOOL")]}),
    ("Der Rohrabschneider liegt in der Garage.", {"entities": [(1, "TOOL")]}),
    ("Die Handsäge ist im Schuppen.", {"entities": [(1, "TOOL")]}),
    ("Hast du den Schaber gesehen?", {"entities": [(3, "TOOL")]}),
    ("Ich kann die Spachtel nicht finden.", {"entities": [(3, "TOOL")]}),
    ("Kannst du mir den Hobel geben?", {"entities": [(4, "TOOL")]}),
    ("Ich habe den Lötbrenner verlegt.", {"entities": [(3, "TOOL")]}),
    ("Wo ist die Trennscheibe?", {"entities": [(3, "TOOL")]}),
    ("Ich finde die Lochzange nicht.", {"entities": [(3, "TOOL")]}),
    ("Kannst du die Kabelschere holen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Bolzenschneider?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Laubsäge gesehen?", {"entities": [(3, "TOOL")]}),
    ("Der Schneidbrenner ist im Keller.", {"entities": [(1, "TOOL")]}),
    ("Kannst du die Nietenzange benutzen?", {"entities": [(3, "TOOL")]}),
    ("Ich habe die Schlagbohrmaschine gebraucht.", {"entities": [(3, "TOOL")]}),
    ("Kannst du den Winkelschleifer holen?", {"entities": [(3, "TOOL")]}),
    ("Ich finde die Abisolierzange nicht.", {"entities": [(3, "TOOL")]}),
    ("Hast du die Auspuffschelle gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Drehspaltkeil?", {"entities": [(3, "TOOL")]}),
    ("Kannst du den Tiefenmesser bringen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Krokodilzange benutzt?", {"entities": [(3, "TOOL")]}),
    ("Ich finde den Sechskantschlüssel nicht.", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Doppelmaulschlüssel?", {"entities": [(3, "TOOL")]}),
    ("Kannst du die Feuchtigkeitsmessgerät holen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Nutfräser gesehen?", {"entities": [(3, "TOOL")]}),
    ("Der Schweißbrenner liegt in der Werkstatt.", {"entities": [(1, "TOOL")]}),
    ("Ich finde den Tackerentferner nicht.", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Kugelhammer?", {"entities": [(2, "TOOL")]}),
    ("Kannst du den Kantenfräser holen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Fugenkratzer gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist die Schnellspannmutter?", {"entities": [(3, "TOOL")]}),
    ("Ich finde den Ringschlüssel nicht.", {"entities": [(3, "TOOL")]}),
    ("Kannst du den Winkelstahlschneider holen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Gipsbeil gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Dreikantschaber?", {"entities": [(3, "TOOL")]}),
    ("Ich finde den Nietdorn nicht.", {"entities": [(3, "TOOL")]}),
    ("Kannst du den Teppichmesser holen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Fliesenschneider gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Fugenmeißel?", {"entities": [(3, "TOOL")]}),
    ("Ich finde den Quergriff nicht.", {"entities": [(3, "TOOL")]}),
    ("Kannst du den Nagelzieher holen?", {"entities": [(3, "TOOL")]}),
    ("Hast du die Abziehlehre gesehen?", {"entities": [(3, "TOOL")]}),
    ("Wo ist der Stechbeitel?", {"entities": [(3, "TOOL")]})
]