TRAIN_DATA = [
    ("Hast du die Zange gesehen?", {"entities": [(12, 16, "TOOL")]}),
    ("Ich brauche den Akkuschrauber um das Regal zu montieren.", {"entities": [(16, 28, "TOOL")]}),
    ("Kannst du den Bohrer holen?", {"entities": [(15, 19, "TOOL")]}),
    ("Das Sägeblatt der Stichsäge ist stumpf.", {"entities": [(4, 12, "TOOL"), (19, 28, "TOOL")]}),
    ("Wir brauchen eine neue Kettensäge für die Gartenarbeit.", {"entities": [(23, 32, "TOOL")]}),
    ("Kannst du die Schleifmaschine einschalten?", {"entities": [(14, 28, "TOOL")]}),
    ("Ich kann nicht finden, wo ich den Schraubenschlüssel hingelegt habe.", {"entities": [(34, 51, "TOOL")]}),
    ("Kannst du den Lötkolben aufheizen?", {"entities": [(14, 22, "TOOL")]}),
    ("Die Stichsäge kann für feine Schnitte verwendet werden.", {"entities": [(4, 13, "TOOL")]}),
    ("Haben wir einen Ersatz für diesen Bohrer?", {"entities": [(34, 39, "TOOL")]}),
    ("Der Winkelschleifer erzeugt viele Funken.", {"entities": [(4, 18, "TOOL")]}),
    ("Hast du den Akkuschrauber aufgeladen?", {"entities": [(12, 24, "TOOL")]}),
    ("Vergiss nicht, den Schraubenzieher zurückzulegen.", {"entities": [(19, 33, "TOOL")]}),
    ("Mit der Säge können wir das Holz zerteilen.", {"entities": [(8, 12, "TOOL")]}),
    ("Kannst du mit dem Tacker diese Papiere zusammenheften?", {"entities": [(18, 23, "TOOL")]}),
    ("Ich benutze die Bohrmaschine für die Wandmontage.", {"entities": [(16, 27, "TOOL")]}),
    ("Pass auf, der Lötkolben ist sehr heiß.", {"entities": [(14, 22, "TOOL")]}),
    ("Der Akkuschrauber hat keinen Saft mehr.", {"entities": [(4, 16, "TOOL")]}),
    ("Hast du den Maulschlüssel gesehen?", {"entities": [(12, 24, "TOOL")]}),
    ("Wir müssen den Fräser austauschen.", {"entities": [(15, 20, "TOOL")]}),
]

