TRAIN_DATA = [
    ("Ich glaube, ich habe das Messer in der Küche gesehen, kannst du nachsehen?", {"entities": [(5, "TOOL")]}),
    ("Nachdem ich den Lötkolben im Werkzeugschrank gelassen habe, kann ich ihn nicht mehr finden.", {"entities": [(3, "TOOL")]}),
    ("Könntest du mir bitte die Zirkel geben, ich brauche sie für mein Mathematikprojekt?", {"entities": [(5, "TOOL")]}),
    ("Trotz meiner Bemühungen kann ich den Steckschlüssel nicht finden, hast du ihn gesehen?", {"entities": [(6, "TOOL")]}),
    ("Falls du einen Schraubstock für diese Aufgabe benötigst, habe ich einen in der Garage.", {"entities": [(3, "TOOL")]}),
    ("Hat jemand den Feile benutzt? Ich kann ihn nicht finden und ich brauche ihn dringend.", {"entities": [(3, "TOOL")]}),
    ("Die Tackerklammern sind fast leer; wir sollten bald neue kaufen.", {"entities": [(1, "TOOL")]}),
    ("Für mein Holzprojekt brauche ich eine neue Gehrungssäge, kannst du mir eine empfehlen?", {"entities": [(7, "TOOL")]}),
    ("Wo hast du die Kneifzange gelassen? Ich habe überall gesucht und kann sie nicht finden.", {"entities": [(4, "TOOL")]}),
    ("Trotz intensiver Suche kann ich den Fräser nicht in der Werkzeugkiste finden, hast du eine Idee, wo er sein könnte?", {"entities": [(6, "TOOL")]}),
    ("Wenn du das Maßband in der Werkstatt siehst, könntest du es mir bitte bringen?", {"entities": [(3, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich den Bolzenschneider im Schuppen gelassen habe.", {"entities": [(8, "TOOL")]}),
    ("Könntest du mir bitte die Laubsäge geben? Ich brauche sie für mein neues Projekt.", {"entities": [(5, "TOOL")]}),
    ("Trotz meiner Bemühungen kann ich die Kabelschere nicht finden, hast du sie gesehen?", {"entities": [(6, "TOOL")]}),
    ("Benötigst du einen Drehmomentschlüssel für diese Reparatur?", {"entities": [(3, "TOOL")]}),
    ("Hat jemand die Abisolierzange benutzt? Ich kann sie nicht finden.", {"entities": [(3, "TOOL")]}),
    ("Die Sicherungszange sind fast leer; wir sollten bald neue kaufen.", {"entities": [(1, "TOOL")]}),
    ("Für meine Arbeit brauche ich eine neue Bohrkrone, kannst du mir eine empfehlen?", {"entities": [(7, "TOOL")]}),
    ("Wo hast du den Diamantbohrer gelassen? Ich habe überall gesucht und kann ihn nicht finden.", {"entities": [(4, "TOOL")]}),
    ("Trotz intensiver Suche kann ich die Zündkerzenzange nicht im Werkzeugkoffer finden, hast du eine Idee, wo sie sein könnte?", {"entities": [(6, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich die Nagelfeile im Badezimmer gelassen habe.", {"entities": [(8, "TOOL")]}),
    ("Wenn du das Winkelmesser in der Schublade siehst, könntest du es mir bitte geben?", {"entities": [(3, "TOOL")]}),
    ("Hat jemand den Flachmeißel benutzt? Ich kann ihn nirgendwo finden.", {"entities": [(3, "TOOL")]}),
    ("Ich könnte schwören, dass ich den Blechschneider hier irgendwo hingelegt habe.", {"entities": [(6, "TOOL")]}),
    ("Benötigst du einen Kreuzschlitzschraubendreher für die Montage des Schranks?", {"entities": [(3, "TOOL")]}),
    ("Die Drahtbürste ist fast abgenutzt; wir sollten bald eine neue kaufen.", {"entities": [(1, "TOOL")]}),
    ("Für mein nächstes Projekt brauche ich eine neue Lochsäge, kannst du mir eine empfehlen?", {"entities": [(8, "TOOL")]}),
    ("Wo hast du den Tackerklammernentferner gelassen? Ich habe überall gesucht und kann ihn nicht finden.", {"entities": [(4, "TOOL")]}),
    ("Trotz intensiver Suche kann ich den Schraubendrehergriff nicht im Werkzeugkoffer finden, hast du eine Idee, wo er sein könnte?", {"entities": [(6, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich die Schlagbohrmaschine im Keller gelassen habe.", {"entities": [(8, "TOOL")]}),
    ("Wenn du den Winkelschleifer in der Werkstatt siehst, könntest du ihn mir bitte bringen?", {"entities": [(3, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich die Schneidzange im Schuppen gelassen habe.", {"entities": [(8, "TOOL")]}),
    ("Könntest du mir bitte den Fuchsschwanz geben? Ich brauche ihn für mein neues Projekt.", {"entities": [(5, "TOOL")]}),
    ("Trotz meiner Bemühungen kann ich die Hobelbank nicht finden, hast du sie gesehen?", {"entities": [(6, "TOOL")]}),
    ("Benötigst du einen Schweißgerät für diese Reparatur?", {"entities": [(3, "TOOL")]}),
    ("Hat jemand den Lötlampe benutzt? Ich kann ihn nicht finden.", {"entities": [(3, "TOOL")]}),
    ("Die Mutternschlüssel sind fast abgenutzt; wir sollten bald neue kaufen.", {"entities": [(1, "TOOL")]}),
    ("Für meine Arbeit brauche ich eine neue Tischkreissäge, kannst du mir eine empfehlen?", {"entities": [(7, "TOOL")]}),
    ("Wo hast du den Schraubendrehergriff gelassen? Ich habe überall gesucht und kann ihn nicht finden.", {"entities": [(4, "TOOL")]}),
    ("Trotz intensiver Suche kann ich den Schraubstock nicht im Werkzeugkasten finden, hast du eine Idee, wo er sein könnte?", {"entities": [(6, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich den Drehmel im Arbeitszimmer gelassen habe.", {"entities": [(8, "TOOL")]}),
    ("Wenn du den Fräser im Lager siehst, könntest du ihn mir bitte geben?", {"entities": [(3, "TOOL")]}),
    ("Hat jemand die Kettensäge benutzt? Ich kann sie nirgendwo finden.", {"entities": [(3, "TOOL")]}),
    ("Ich könnte schwören, dass ich die Sackkarre hier irgendwo hingelegt habe.", {"entities": [(6, "TOOL")]}),
    ("Benötigst du einen Gabelschlüssel für die Montage des Fahrrads?", {"entities": [(3, "TOOL")]}),
    ("Die Rohrzange ist fast abgenutzt; wir sollten bald eine neue kaufen.", {"entities": [(1, "TOOL")]}),
    ("Für mein nächstes Projekt brauche ich eine neue Schwingschleifer, kannst du mir eine empfehlen?", {"entities": [(8, "TOOL")]}),
    ("Wo hast du den Trennschleifer gelassen? Ich habe überall gesucht und kann ihn nicht finden.", {"entities": [(4, "TOOL")]}),
    ("Trotz intensiver Suche kann ich den Schraubendreher nicht im Werkzeugschrank finden, hast du eine Idee, wo er sein könnte?", {"entities": [(6, "TOOL")]}),
    ("Ich bin mir ziemlich sicher, dass ich den Flachmeißel in der Garage gelassen habe.", {"entities": [(8, "TOOL")]})
]
