TRAIN_DATA = [
    ("Ich brauche einen Schraubenzieher, um die Schrauben festzuziehen.", {"entities": [(12, 27, "TOOL")]}),
    ("Die Bohrmaschine ist sehr laut.", {"entities": [(4, 18, "TOOL")]}),
    ("Ich verwende den Schraubenschlüssel, um die Muttern festzuziehen.", {"entities": [(13, 31, "TOOL")]}),
    ("Die Zange ist ein vielseitiges Werkzeug.", {"entities": [(4, 10, "TOOL")]}),
    ("Mit dem Akkuschrauber geht das schneller.", {"entities": [(8, 22, "TOOL")]}),
    ("Der Schraubendreher ist in verschiedenen Größen erhältlich.", {"entities": [(4, 19, "TOOL")]}),
    ("Ich brauche einen Hammer, um den Nagel einzuschlagen.", {"entities": [(13, 20, "TOOL")]}),
    ("Die Säge ist sehr scharf.", {"entities": [(4, 9, "TOOL")]}),
    ("Ich benutze die Kombizange, um Drähte abzuschneiden.", {"entities": [(10, 20, "TOOL")]}),
    ("Der Schraubstock hält das Werkstück fest.", {"entities": [(4, 15, "TOOL")]}),
    ("Der Seitenschneider ist gut für das Schneiden von Kabeln.", {"entities": [(4, 21, "TOOL")]}),
    ("Die Wasserwaage hilft bei der genauen Ausrichtung.", {"entities": [(4, 16, "TOOL")]}),
    ("Ich habe einen Inbusschlüssel in meinem Werkzeugkasten.", {"entities": [(12, 24, "TOOL")]}),
    ("Das Messer ist sehr scharf und gut zum Schneiden.", {"entities": [(4, 10, "TOOL")]}),
    ("Mit dem Lötkolben kann ich Elektronik löten.", {"entities": [(8, 18, "TOOL")]}),
    ("Die Kettensäge eignet sich gut für das Schneiden von Holz.", {"entities": [(4, 15, "TOOL")]}),
    ("Der Steckschlüsselsatz enthält verschiedene Größen.", {"entities": [(4, 24, "TOOL")]}),
    ("Ich benutze die Flachzange für präzises Greifen.", {"entities": [(14, 24, "TOOL")]}),
    ("Der Multischrauber vereint verschiedene Funktionen.", {"entities": [(4, 20, "TOOL")]}),
    ("Das Cuttermesser ist praktisch für das Schneiden von Materialien.", {"entities": [(4, 16, "TOOL")]}),
    ("Mit dem Meißel kann ich Holz schnitzen.", {"entities": [(8, 15, "TOOL")]}),
    ("Der Maulschlüssel ist gut für das Festziehen von Muttern.", {"entities": [(4, 17, "TOOL")]})]